server:
  port: 8881
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/extra-profile?createDatabaseIfNotExist=true
    username: root
    password: pass1w0rd#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
      